# Generated by Django 3.2.5 on 2021-07-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('problem_slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='NULL', max_length=4)),
                ('topic', models.CharField(blank=True, max_length=24, null=True)),
                ('related_topics', models.JSONField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('problem', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='question.problem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdownFile', models.FileField(blank=True, null=True, upload_to='')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.problem')),
            ],
        ),
    ]
