# Generated by Django 3.2.5 on 2021-07-05 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(blank=True, max_length=64, null=True)),
                ('question_slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='NULL',
                                                max_length=4)),
                ('topic', models.CharField(blank=True, max_length=24, null=True)),
                ('related_topics', models.JSONField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdownFile', models.FileField(blank=True, null=True, upload_to='')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='lcAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_user', models.CharField(max_length=64)),
                ('lc_pass', models.CharField(max_length=64)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
