# Generated by Django 3.2.5 on 2021-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
