# Generated by Django 3.2.5 on 2021-07-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('LCuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.lcauth')),
                ('question',
                 models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
