# Generated by Django 3.2.5 on 2021-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_solution_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['user', 'problem'], name='question_so_user_id_f67cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['problem'], name='question_so_problem_bff731_idx'),
        ),
    ]
