# Generated by Django 3.2.5 on 2021-07-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0002_auto_20210705_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='QuestionFile',
            new_name='ProblemFile',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='question_name',
            new_name='problem_name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='question_slug',
            new_name='problem_slug',
        ),
        migrations.RenameField(
            model_name='problemfile',
            old_name='question',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='question',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='solution',
            name='LCuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='question.lcauth'),
        ),
    ]
