# Generated by Django 3.2.5 on 2021-07-08 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0004_solution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='LCuser',
        ),
    ]
