# Generated by Django 3.2.5 on 2021-07-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0005_remove_solution_lcuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='question.problem'),
        ),
    ]
